/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.Controladora;
import Modelo.Users;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Administrador extends javax.swing.JFrame {
    Controladora control = new Controladora();
    DefaultTableModel md;
    /**
     * Creates new form Administrador
     */
    public Administrador(String userID) {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton4.setVisible(false);
        panelCrearUsuario.setVisible(false);
        panelModificarUsuario.setVisible(false);
        panelEstadoUsuario.setVisible(false);
        
        Users profileInfo = control.consultProfile(userID);
        this.id_admin.setText(profileInfo.getId());
        this.nombre_admin.setText(profileInfo.getFname());
        this.apellido_admin.setText(profileInfo.getLname());
        this.telefono_admin.setText(profileInfo.getTel());
        this.direccion_admin.setText(profileInfo.getDir().trim());
        
        String data[][] = {};
        String columnNames[] = {"Cedula", "Nombre", "Apellido", "Telefono", "Cargo", "Estado"};
        md = new DefaultTableModel(data, columnNames);
        tablaUsuarios.setModel(md);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonGenerarFacturas = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SignOut = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelAdministrador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_admin = new javax.swing.JTextField();
        nombre_admin = new javax.swing.JTextField();
        apellido_admin = new javax.swing.JTextField();
        telefono_admin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        direccion_admin = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        panelEstadoUsuario = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldcedulaEstado = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        botonCambiarEstado = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldCedulaConsultaEstado = new javax.swing.JTextField();
        botonConsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        resultadoConsultaEstadoUsuario = new javax.swing.JTextField();
        panelModificarUsuario = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldCedulaModificar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxAtributo = new javax.swing.JComboBox<>();
        BotonModificarUsuario = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNuevoValor = new javax.swing.JTextField();
        cargoModificar = new javax.swing.JComboBox<>();
        nuevoValorCargo = new javax.swing.JLabel();
        panelCrearUsuario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botonCrearUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPaterno = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldMaterno = new javax.swing.JTextField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        panelListarUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        botonListarUsuarios = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 60, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Usuario");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 212, 175, 29));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Configurar el sistema");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 267, 175, 29));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Perfil");
        jButton4.setToolTipText("");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 175, 29));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modificar Usuario");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 324, 175, 29));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Estado del Usuario");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 175, 29));

        jButtonGenerarFacturas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonGenerarFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGenerarFacturas.setText("Generar Facturas");
        jButtonGenerarFacturas.setBorder(null);
        jButtonGenerarFacturas.setBorderPainted(false);
        jButtonGenerarFacturas.setContentAreaFilled(false);
        jButtonGenerarFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGenerarFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGenerarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarFacturasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerarFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 175, 29));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Listar Usuarios");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 175, 29));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Multiply_25px.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(646, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        SignOut.setBackground(new java.awt.Color(255, 255, 255));
        SignOut.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        SignOut.setBorderPainted(false);
        SignOut.setContentAreaFilled(false);
        SignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignOut.setFocusable(false);
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(SignOut)
                .addGap(294, 294, 294))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 681, 60));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdministrador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel1.setText("Perfil Administrador");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Teléfono:");

        id_admin.setEditable(false);
        id_admin.setBackground(new java.awt.Color(255, 255, 255));
        id_admin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        id_admin.setBorder(null);
        id_admin.setSelectionColor(new java.awt.Color(204, 204, 204));

        nombre_admin.setEditable(false);
        nombre_admin.setBackground(new java.awt.Color(255, 255, 255));
        nombre_admin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nombre_admin.setBorder(null);
        nombre_admin.setSelectionColor(new java.awt.Color(204, 204, 204));

        apellido_admin.setEditable(false);
        apellido_admin.setBackground(new java.awt.Color(255, 255, 255));
        apellido_admin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        apellido_admin.setBorder(null);
        apellido_admin.setSelectionColor(new java.awt.Color(204, 204, 204));

        telefono_admin.setEditable(false);
        telefono_admin.setBackground(new java.awt.Color(255, 255, 255));
        telefono_admin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        telefono_admin.setBorder(null);
        telefono_admin.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Dirección:");

        direccion_admin.setEditable(false);
        direccion_admin.setBackground(new java.awt.Color(255, 255, 255));
        direccion_admin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        direccion_admin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        direccion_admin.setBorder(null);
        direccion_admin.setMinimumSize(new java.awt.Dimension(1, 30));
        direccion_admin.setSelectionColor(new java.awt.Color(204, 204, 204));
        direccion_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_adminActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N

        javax.swing.GroupLayout panelAdministradorLayout = new javax.swing.GroupLayout(panelAdministrador);
        panelAdministrador.setLayout(panelAdministradorLayout);
        panelAdministradorLayout.setHorizontalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministradorLayout.createSequentialGroup()
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministradorLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAdministradorLayout.createSequentialGroup()
                                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel18))
                                .addGap(86, 86, 86)
                                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefono_admin)
                                    .addComponent(apellido_admin)
                                    .addComponent(nombre_admin)
                                    .addComponent(id_admin)
                                    .addComponent(direccion_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                            .addComponent(jLabel1)))
                    .addGroup(panelAdministradorLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel26)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        panelAdministradorLayout.setVerticalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministradorLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(28, 28, 28)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nombre_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(apellido_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(telefono_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdministradorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18))
                    .addGroup(panelAdministradorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(direccion_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 681, 615));

        panelEstadoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelEstadoUsuario.setPreferredSize(new java.awt.Dimension(680, 587));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel20.setText("Estado del Usuario");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setText("Cedula");

        jTextFieldcedulaEstado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Nuevo Estado");

        jComboBoxEstado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        botonCambiarEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonCambiarEstado.setText("Cambiar Estado");
        botonCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarEstadoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 22)); // NOI18N
        jLabel23.setText("Cambio de Estado:");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 22)); // NOI18N
        jLabel24.setText("Consultar Estado:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel25.setText("Cedula");

        jTextFieldCedulaConsultaEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        botonConsultar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });

        resultadoConsultaEstadoUsuario.setEditable(false);
        resultadoConsultaEstadoUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout panelEstadoUsuarioLayout = new javax.swing.GroupLayout(panelEstadoUsuario);
        panelEstadoUsuario.setLayout(panelEstadoUsuarioLayout);
        panelEstadoUsuarioLayout.setHorizontalGroup(
            panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoUsuarioLayout.createSequentialGroup()
                .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstadoUsuarioLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEstadoUsuarioLayout.createSequentialGroup()
                                .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldcedulaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addComponent(botonCambiarEstado))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEstadoUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCedulaConsultaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(botonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultadoConsultaEstadoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelEstadoUsuarioLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel20)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelEstadoUsuarioLayout.setVerticalGroup(
            panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoUsuarioLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel20)
                .addGap(30, 30, 30)
                .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstadoUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldcedulaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonCambiarEstado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstadoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedulaConsultaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultar))
                .addGap(18, 18, 18)
                .addComponent(resultadoConsultaEstadoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );

        jLayeredPane1.add(panelEstadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 681, 615));

        panelModificarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelModificarUsuario.setPreferredSize(new java.awt.Dimension(680, 587));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel14.setText("Modificar Usuario");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Cedula");

        jTextFieldCedulaModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCedulaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaModificarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Campo a Cambiar");

        jComboBoxAtributo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxAtributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre_persona", "paterno_persona", "materno_persona", "telefono_usuario", "direccion_persona", "tipo_usuario", "password_usuario" }));
        jComboBoxAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAtributoActionPerformed(evt);
            }
        });

        BotonModificarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonModificarUsuario.setText("Modificar");
        BotonModificarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModificarUsuarioMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Nuevo Valor");

        jTextFieldNuevoValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cargoModificar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cargoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gerente", "Operador" }));
        cargoModificar.setVisible(false);
        cargoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoModificarActionPerformed(evt);
            }
        });

        nuevoValorCargo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nuevoValorCargo.setText("Nuevo Valor");
        nuevoValorCargo.setVisible(false);

        javax.swing.GroupLayout panelModificarUsuarioLayout = new javax.swing.GroupLayout(panelModificarUsuario);
        panelModificarUsuario.setLayout(panelModificarUsuarioLayout);
        panelModificarUsuarioLayout.setHorizontalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(BotonModificarUsuario)
                    .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nuevoValorCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldNuevoValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(jComboBoxAtributo, javax.swing.GroupLayout.Alignment.LEADING, 0, 195, Short.MAX_VALUE)
                            .addComponent(jTextFieldCedulaModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(cargoModificar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 231, Short.MAX_VALUE))
        );
        panelModificarUsuarioLayout.setVerticalGroup(
            panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarUsuarioLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel14)
                .addGap(43, 43, 43)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedulaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoValorCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNuevoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BotonModificarUsuario)
                .addGap(165, 165, 165))
        );

        jLayeredPane1.add(panelModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 681, 615));

        panelCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelCrearUsuario.setPreferredSize(new java.awt.Dimension(680, 587));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel6.setText("Crear Usuario");

        botonCrearUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonCrearUsuario.setText("Crear Usuario");
        botonCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearUsuarioMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Cedula");
        jLabel7.setAlignmentX(1.0F);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Telefono");
        jLabel8.setAlignmentX(1.0F);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Nombre");
        jLabel9.setAlignmentX(1.0F);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Apellido Paterno");
        jLabel10.setAlignmentX(1.0F);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Direccion");
        jLabel11.setAlignmentX(1.0F);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Posicion trabajo");
        jLabel12.setAlignmentX(1.0F);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Contraseña");
        jLabel13.setAlignmentX(1.0F);

        jTextFieldCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCedula.setAlignmentX(1.0F);

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNombre.setAlignmentX(1.0F);

        jTextFieldPaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPaterno.setAlignmentX(1.0F);
        jTextFieldPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPaternoActionPerformed(evt);
            }
        });

        jTextFieldTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldTelefono.setAlignmentX(1.0F);

        jTextFieldDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDireccion.setAlignmentX(1.0F);

        jComboBoxCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gerente", "Operador" }));
        jComboBoxCargo.setAlignmentX(1.0F);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel28.setText("Apellido Materno");
        jLabel28.setAlignmentX(1.0F);

        jTextFieldMaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMaterno.setAlignmentX(1.0F);
        jTextFieldMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaternoActionPerformed(evt);
            }
        });

        jPasswordFieldContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldContrasena.setAlignmentX(1.0F);

        javax.swing.GroupLayout panelCrearUsuarioLayout = new javax.swing.GroupLayout(panelCrearUsuario);
        panelCrearUsuario.setLayout(panelCrearUsuarioLayout);
        panelCrearUsuarioLayout.setHorizontalGroup(
            panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                            .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addGap(54, 54, 54)
                            .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldTelefono)
                                .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxCargo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearUsuarioLayout.createSequentialGroup()
                            .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearUsuario)
                .addGap(238, 238, 238))
        );
        panelCrearUsuarioLayout.setVerticalGroup(
            panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearUsuarioLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(17, 17, 17)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(botonCrearUsuario)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 681, 615));

        panelListarUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Dirección", "Tipo Usuario", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setEnabled(false);
        jScrollPane1.setViewportView(tablaUsuarios);

        botonListarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonListarUsuarios.setText("Listar");
        botonListarUsuarios.setToolTipText("");
        botonListarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListarUsuariosMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        jLabel27.setText("Usuario Ingresados");

        javax.swing.GroupLayout panelListarUsuariosLayout = new javax.swing.GroupLayout(panelListarUsuarios);
        panelListarUsuarios.setLayout(panelListarUsuariosLayout);
        panelListarUsuariosLayout.setHorizontalGroup(
            panelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(botonListarUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListarUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(177, 177, 177))
        );
        panelListarUsuariosLayout.setVerticalGroup(
            panelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(botonListarUsuarios)
                .addContainerGap())
        );

        jLayeredPane1.add(panelListarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 681, 470));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 39, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panelAdministrador.setVisible(true);
        panelEstadoUsuario.setVisible(false);
        panelModificarUsuario.setVisible(false);
        panelCrearUsuario.setVisible(false);
        panelListarUsuarios.setVisible(false);

        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton4.setVisible(false);
        jButton3.setVisible(true);
        jButton7.setVisible(true);
        jButtonGenerarFacturas.setVisible(true);
        jButton9.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelAdministrador.setVisible(false);
        panelEstadoUsuario.setVisible(false);
        panelModificarUsuario.setVisible(false);
        panelCrearUsuario.setVisible(true);
        panelListarUsuarios.setVisible(false);

        jButton1.setVisible(false);
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(true);
        jButton7.setVisible(true);
        jButtonGenerarFacturas.setVisible(true);
        jButton9.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        panelAdministrador.setVisible(false);
        panelEstadoUsuario.setVisible(false);
        panelModificarUsuario.setVisible(true);
        panelCrearUsuario.setVisible(false);
        panelListarUsuarios.setVisible(false);

        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(false);
        jButton7.setVisible(true);
        jButtonGenerarFacturas.setVisible(true);
        jButton9.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldCedulaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaModificarActionPerformed

    private void jComboBoxAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAtributoActionPerformed
        if (jComboBoxAtributo.getItemAt(jComboBoxAtributo.getSelectedIndex()).equals("tipo_usuario")){
            nuevoValorCargo.setVisible(true);
            cargoModificar.setVisible(true);
            jLabel19.setVisible(false);
            jTextFieldNuevoValor.setText(cargoModificar.getItemAt(cargoModificar.getSelectedIndex()));
            jTextFieldNuevoValor.setEditable(false);            
        }else {
            nuevoValorCargo.setVisible(false);
            cargoModificar.setVisible(false);
            jLabel19.setVisible(true);
            jTextFieldNuevoValor.setEditable(true);
        }
    }//GEN-LAST:event_jComboBoxAtributoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        panelAdministrador.setVisible(false);
        panelEstadoUsuario.setVisible(true);
        panelModificarUsuario.setVisible(false);
        panelCrearUsuario.setVisible(false);
        panelListarUsuarios.setVisible(false);

        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(true);
        jButton7.setVisible(false);
        jButtonGenerarFacturas.setVisible(true);
        jButton9.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void botonCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarEstadoActionPerformed
        if (jTextFieldcedulaEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error, tienes elementos vacios");
        } else {
            try {
                int identification = Integer.parseInt(jTextFieldcedulaEstado.getText());
                if (identification < 0) {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                } else if (control.updateUser(jTextFieldcedulaEstado.getText(), "estado_usuario", jComboBoxEstado.getItemAt(jComboBoxEstado.getSelectedIndex()))) {
                    this.cleanCreateSection();
                    JOptionPane.showMessageDialog(null, "Estado modificado exitosamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "La Cedula debe ser un entero");
            }
        }
    }//GEN-LAST:event_botonCambiarEstadoActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        resultadoConsultaEstadoUsuario.setText("");
        if (jTextFieldCedulaConsultaEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error, tienes elementos vacios");
        } else {
            try {
                int identification = Integer.parseInt(jTextFieldCedulaConsultaEstado.getText());
                if (identification < 0) {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                } else { 
                    control.consultProfile(jTextFieldCedulaConsultaEstado.getText());                    
                    resultadoConsultaEstadoUsuario.setText("El usuario con cedula " + jTextFieldCedulaConsultaEstado.getText() + " se encuentra " + control.consultProfile(jTextFieldCedulaConsultaEstado.getText()).getState());
                    this.cleanCreateSection();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "La Cedula debe ser un entero");
            }
        }
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void jTextFieldPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPaternoActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        login2 log = new login2();
        log.setLocationRelativeTo(null);
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignOutActionPerformed

    private void BotonModificarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarUsuarioMouseClicked
        if (jTextFieldCedulaModificar.getText().equals("") || jTextFieldNuevoValor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error, tienes elementos vacios");
        } else {
            try {
                int identification = Integer.parseInt(jTextFieldCedulaModificar.getText());
                if (identification < 0) {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                } else if (control.updateUser(jTextFieldCedulaModificar.getText(), jComboBoxAtributo.getItemAt(jComboBoxAtributo.getSelectedIndex()), jTextFieldNuevoValor.getText())) {
                    this.cleanCreateSection();
                    JOptionPane.showMessageDialog(null, "Usuario modificado exitosamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "La Cedula debe ser un entero");
            }
        }
    }//GEN-LAST:event_BotonModificarUsuarioMouseClicked

    private void botonCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearUsuarioMouseClicked
        if (jTextFieldCedula.getText().equals("") || jTextFieldNombre.getText().equals("") || jTextFieldPaterno.getText().equals("") || jTextFieldTelefono.getText().equals("") || jTextFieldDireccion.getText().equals("") || jPasswordFieldContrasena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error, tienes elementos vacios");
        } else {
            try {
                int identification = Integer.parseInt(jTextFieldCedula.getText());
                if (identification < 0) {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                } else if (control.createUser(jTextFieldCedula.getText(), jTextFieldNombre.getText(), jTextFieldPaterno.getText(), jTextFieldMaterno.getText(),jTextFieldTelefono.getText(), jTextFieldDireccion.getText(), jComboBoxCargo.getItemAt(jComboBoxCargo.getSelectedIndex()), jPasswordFieldContrasena.getText())) {
                    this.cleanCreateSection();
                    JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos Incorrectos \nIntentalo Nuevamente");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "La Cedula debe ser un entero");
            }
        }
    }//GEN-LAST:event_botonCrearUsuarioMouseClicked

    private void jTextFieldMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaternoActionPerformed

    private void direccion_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_adminActionPerformed

    private void jButtonGenerarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarFacturasActionPerformed
        
        /*String nombreCliente="aqui va el nombre cliente";
        String direccion="esta es su direccion";
        String cedula="aqui es la cedula";
        String rutaImagen="C:\\Users\\Jesús\\Downloads\\Logotelefonica1.jpeg";
        String infoCliente="\n\n    cliente  " + nombreCliente + "\n    direccion  " + direccion + "\n    cedula  " + cedula+ "\n    Fecha de expedición x" + "\n    Factura de venta n"+ "\n\n\n\n";
        String infoPago="  aqui iria la tabla con valor a pagar fechas etc\n\n\n\n";
        String resumenCuenta="  aquí va la info de pagos atrasados si los hay o deucdas y el Total a pagar otra vez";
        String rutaGuardar="C:\\Users\\Jesús\\Desktop\\fatura.pdf";
        String facturasPendientes="";
        String serviciosAdicionales="";
        String valorMesActual="";
        String totalaPagar="";
        Factura g= new Factura();
        g.generarPDF(rutaImagen, infoCliente, infoPago, resumenCuenta, rutaGuardar, facturasPendientes,serviciosAdicionales,valorMesActual, totalaPagar);*/
        control.generarFacturaClients();
        jButtonGenerarFacturas.setVisible(true);
        JOptionPane.showMessageDialog(null, "Factura generada exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGenerarFacturasActionPerformed

    private void botonListarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListarUsuariosMouseClicked
        listarUsuarios();
    }//GEN-LAST:event_botonListarUsuariosMouseClicked

    private void cargoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoModificarActionPerformed
        jTextFieldNuevoValor.setText(cargoModificar.getItemAt(cargoModificar.getSelectedIndex()));
    }//GEN-LAST:event_cargoModificarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        panelAdministrador.setVisible(false);
        panelEstadoUsuario.setVisible(false);
        panelModificarUsuario.setVisible(false);
        panelCrearUsuario.setVisible(false);
        panelListarUsuarios.setVisible(true);

        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton4.setVisible(true);
        jButton3.setVisible(true);
        jButton7.setVisible(true);
        jButtonGenerarFacturas.setVisible(true);
        jButton9.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void listarUsuarios(){
        md.setRowCount(0); //Para limpiar la tabla
        ArrayList<String[]> lista = control.listarUsers();
        for (int i = 0; i < lista.size(); i++) {
            md.addRow(lista.get(i));
            
        }
    }
    
    private void cleanCreateSection() {
        jTextFieldCedula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldPaterno.setText("");
        jTextFieldMaterno.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldDireccion.setText("");
        jPasswordFieldContrasena.setText("");
        jTextFieldcedulaEstado.setText("");
        jTextFieldNuevoValor.setText("");
        jTextFieldCedulaConsultaEstado.setText("");
        jTextFieldCedulaModificar.setText("");                
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModificarUsuario;
    private javax.swing.JButton SignOut;
    private javax.swing.JTextField apellido_admin;
    private javax.swing.JButton botonCambiarEstado;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonListarUsuarios;
    private javax.swing.JComboBox<String> cargoModificar;
    private javax.swing.JLabel cerrar;
    private javax.swing.JTextField direccion_admin;
    private javax.swing.JTextField id_admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonGenerarFacturas;
    private javax.swing.JComboBox<String> jComboBoxAtributo;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldCedulaConsultaEstado;
    private javax.swing.JTextField jTextFieldCedulaModificar;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldMaterno;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNuevoValor;
    private javax.swing.JTextField jTextFieldPaterno;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldcedulaEstado;
    private javax.swing.JTextField nombre_admin;
    private javax.swing.JLabel nuevoValorCargo;
    private javax.swing.JPanel panelAdministrador;
    private javax.swing.JPanel panelCrearUsuario;
    private javax.swing.JPanel panelEstadoUsuario;
    private javax.swing.JPanel panelListarUsuarios;
    private javax.swing.JPanel panelModificarUsuario;
    private javax.swing.JTextField resultadoConsultaEstadoUsuario;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField telefono_admin;
    // End of variables declaration//GEN-END:variables
}
